POST http://localhost:5000/api/users/signup HTTP/1.1
content-Type: application/json

{
    "name": "Kim",
    "email": "naneun@gmail.com",
    "password": "naneun"
}

###
POST http://localhost:5000/api/users/login HTTP/1.1
content-Type: application/json

{
    "email": "naneun@gmail.com",
    "password": "naneun"
}


GET http://localhost:5000/api/users/
